### ISSUE TITLE
MySQLdb

### ISSUE THREAD

**Issue by slashw** [Jerrythafast/se-logger#6]
Loop tegen het volgend probleem aan.
Traceback (most recent call last):
  File "/opt/se-logger/liveupdate.py", line 24, in <module>
    import struct, sys, MySQLdb, time
ModuleNotFoundError: No module named 'MySQLdb'

Na heel wat zoeken blijkt dat MySQLdb niet door python 3... word ondersteund. Is dat ook zo?

Ik gebruik versie 0.0.15

Wim

**Comment by Jerrythafast** [comment]
Will respond in English because this can be useful for others.
The question is: MySQLdb does not appear to support python3. Is that so?

The answer is: The original MySQLdb maintainers have not (yet?) updated their package to support python3. Instead, an updated fork of MySQLdb is available named [mysqlclient](https://pypi.org/project/mysqlclient/). That's the one you need. (Ubuntu users can use `apt install python3-mysql` as written in the readme; if your OS does not offer a similar package you can always resort to `pip3 install mysqlclient`.)
